image: Visual Studio 2019
version: 0.0.0.{build}
platform: Any CPU
skip_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  assembly_file_version: $(APPVEYOR_BUILD_VERSION)
  assembly_informational_version: $(APPVEYOR_BUILD_VERSION)
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(APPVEYOR_BUILD_VERSION)
  package_version: $(APPVEYOR_BUILD_VERSION)
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  file_version: $(APPVEYOR_BUILD_VERSION)
  informational_version: $(APPVEYOR_BUILD_VERSION)

environment:
  github_access_token:
    secure: 3n2WMbrqWb0nmy2LBmu7w6dJltiHHC4LCoNuIKBh7fKV0xfxCwVGOxbTpunLI2pe
  codesignaes:
    secure: 9f78dD9jN5vlVZ0zv15kdD4Mj+/+uacfu29bbGC+cBVFs834aFVf5Ci+n3NP3Bl7
  codesignpasswd:
    secure: iKv14aGuHUDEfb5fSIBMuSsu1JnisWXL8wJ7x/2DCNtggWKevjhOFBOrI7c95xBY

cache:
  - packages

install:
  - ps: ./CI/appveyor_install.ps1

before_build:
  - nuget restore -Verbosity quiet
  - msbuild /nologo /v:m /t:Clean

build_script:
  - ps: msbuild /nologo /v:m /p:Configuration="$env:CONFIGURATION" /p:SquirrelBuildTarget="$env:DEPLOY_SITE_GIT\BililiveRecorder" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: msbuild /nologo /v:m /t:BililiveRecorder_Cli:Publish /p:Configuration="$env:CONFIGURATION" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: msbuild /nologo /v:m /t:BililiveRecorder_Cli:Publish /p:Configuration="$env:CONFIGURATION" /p:RuntimeIdentifier="linux-arm" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: msbuild /nologo /v:m /t:BililiveRecorder_Cli:Publish /p:Configuration="$env:CONFIGURATION" /p:RuntimeIdentifier="linux-arm64" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: msbuild /nologo /v:m /t:BililiveRecorder_Cli:Publish /p:Configuration="$env:CONFIGURATION" /p:RuntimeIdentifier="linux-x64" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: msbuild /nologo /v:m /t:BililiveRecorder_Cli:Publish /p:Configuration="$env:CONFIGURATION" /p:RuntimeIdentifier="osx.10.11-x64" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: msbuild /nologo /v:m /t:BililiveRecorder_Cli:Publish /p:Configuration="$env:CONFIGURATION" /p:RuntimeIdentifier="osx-x64" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: msbuild /nologo /v:m /t:BililiveRecorder_Cli:Publish /p:Configuration="$env:CONFIGURATION" /p:RuntimeIdentifier="win-x64" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

for:
-
  branches:
    only:
      - master # including pull requests target at master
  configuration: Release
  before_deploy: # wont run on pull request
    - ps: ./CI/appveyor_deploy.ps1
  deploy: # wont run on pull request
    provider: GitHub
    release: v$(APPVEYOR_BUILD_VERSION)
    description: '# ◁☆Fill out this before publish☆▷'
    auth_token:
      secure: 3n2WMbrqWb0nmy2LBmu7w6dJltiHHC4LCoNuIKBh7fKV0xfxCwVGOxbTpunLI2pe
    artifact: github
    draft: true
-
  configuration: Debug
  artifacts:
    - path: BililiveRecorder.WPF\bin\Debug
      name: BililiveRecorderWPFDebugBuild
    - path: BililiveRecorder.Cli\publish\any
      name: BililiveRecorderCliDebugBuild
    - path: BililiveRecorder.Cli\publish\linux-arm
      name: BililiveRecorderCliDebugBuild-linux-arm
    - path: BililiveRecorder.Cli\publish\linux-arm64
      name: BililiveRecorderCliDebugBuild-linux-arm64
    - path: BililiveRecorder.Cli\publish\linux-x64
      name: BililiveRecorderCliDebugBuild-linux-x64
    - path: BililiveRecorder.Cli\publish\osx.10.11-x64
      name: BililiveRecorderCliDebugBuild-osx.10.11-x64
    - path: BililiveRecorder.Cli\publish\osx-x64
      name: BililiveRecorderCliDebugBuild-osx-x64
    - path: BililiveRecorder.Cli\publish\win-x64
      name: BililiveRecorderCliDebugBuild-win-x64

on_finish:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
